# Generated by Django 6.0.2 on 2026-02-08 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
