# Generated by Django 6.0.2 on 2026-02-08 09:49

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0002_groupchat_online_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='groupname',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True),
        ),
    ]
