# Generated by Django 6.0.2 on 2026-02-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0009_userchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='recent_msg_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
