# Generated by Django 6.0.2 on 2026-02-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0010_groupchat_recent_msg_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'ordering': ['-recent_msg_at']},
        ),
    ]
