# Generated by Django 6.0.2 on 2026-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0011_alter_groupchat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
