# Generated by Django 6.0.2 on 2026-02-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0012_groupmessage_file_alter_groupmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='groupname',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
