# Generated by Django 6.0.2 on 2026-02-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0013_alter_groupchat_groupname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={},
        ),
    ]
