# Generated by Django 6.0.2 on 2026-02-11 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0014_alter_groupchat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'ordering': ['-recent_msg_at']},
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='groupname',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True),
        ),
    ]
